apiVersion: autoscale.example.com/v1
kind: AppScaler
metadata:
  labels:
    app.kubernetes.io/name: scale-operator
    app.kubernetes.io/managed-by: kustomize
  name: appscaler-sample
spec:
  # TODO(user): Add fields here
