apiVersion: autoscale.example.com/v1
kind: AppScaler
metadata:
  labels:
    app.kubernetes.io/name: scale-operator
    app.kubernetes.io/managed-by: kustomize
  name: appscaler-sample
spec:
  deploymentName: sample-worker
  namespace: default
  subject: test
  natsMonitoringUrl: http://nats.nats.svc.cluster.local:8222
  stream: mystream
  consumer: myconsumer
  minReplicas: 1
  maxReplicas: 5
  scaleUpThreshold: 10
  scaleDownThreshold: 2
  pollIntervalSeconds: 15
