apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-worker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-worker
  template:
    metadata:
      labels:
        app: sample-worker
    spec:
      containers:
      - name: worker
        image: busybox
        command: ["sleep", "3600"]

